manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    # Imports the official Zephyr OS
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.3.0
      import: true
      path: zephyr

  self:
    path: app